/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module scm_10( 
	input wire clk, rst,
	input wire signed [31:0]X,
	output reg signed [31:0]Y
 
);


  //Multipliers:

  reg signed [51:0]
    w1,
    w4,
    w5,
    w10485760; 
	
	
	always @(posedge clk or posedge rst)begin 
		if (rst) begin
			Y = 32'b0;
		end else begin 
		  w1 = X;
		  w4 = w1 << 2;
		  w5 = w1 + w4;
		  w10485760 = w5 << 21;
		
		  Y = w10485760[51:20]; 
  	end		   
end


endmodule //multiplier_block
